spring.application.name=asm01

# DATABASE (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/course_management
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# SQL LOG
spring.jpa.show-sql=true
